Boostrap5 make Expires and Burn after reading more prominant
PrivateBin/PrivateBin pull request #1414
Opened 2024-10-08 13:47 UTC by FingerlessGlov3s

I personally like making `Expires` and `Burn after reading` more prominant, show the options exist more clearly. Which should hopefully lead to people thinking about using the options, rather than skimming over them with the normal font colour.

## Changes
* Make `Expires` text red
* Make `Burn after reading` text orange

2024-10-08 19:34 UTC, elrido commented
I appreciate you taking the time to submit this PR and that you picked a solution based on bootstrap CSS default classes. What are the other maintainers opinions on this one, @r4sas & @rugk?

2024-10-16 18:40 UTC, rugk commented
Defined classes or not, this just makes the UI a lot more colorful… without keeping any design aspect.

IMHO just making things red and yellow is not the way to go and personally hurts my eyes. If we'd have to emphasize such a thing, we could use some icons or whatever, but not random colors outside of any color palette or so.

2024-10-16 18:42 UTC, rugk requested changes
Also, the used classes also show they don't convoy what you wanted to convey… expires is neither dangerious nor is burnafterread a warning…

So I propose to decline this PR or find an alternative solution to the actual problem… what was it, actually? You did not find these options hmm? IMHO, they are already probably pretty visible in the top toolbar.

2024-10-17 06:51 UTC, closed without merging

2024-10-17 06:51 UTC, elrido commented
Ok, in that case I'll close the PR, but yes, of course you and others can now find and apply this change to your own custom templates. Thank you for sharing it here with us!