Avoid the use of <i> markup in a translation.
PrivateBin/PrivateBin pull request #756
Opened 2021-02-28 14:21 UTC by hogren

This PR fixes a problem introduced with the commit eb32ea141956c0ed72e3186956895333f62e271c.
In the sentence "Data is encrypted/decrypted in the browser using 256 bits AES.", we saw "&lt;i&gt;in the browser&lt;/i&gt;" in normal font style in place of "<i>in the browser</i>" in italic.

## Changes

As discussed on the [PR 755](https://github.com/PrivateBin/PrivateBin/pull/755), and [PR 754](https://github.com/PrivateBin/PrivateBin/pull/754), I keep the entire sentence in one translation object. I use sprintf to insert &lt;i&gt; and &lt;/i&gt;. Because I18n library already use sprintf (but escape HTML code in each argument), I need to tell it to explicitly return "%s" in the place where I need to insert the markups.

## ToDo
If it's ok, I will try to do the same work for all HTML markups currently present in translations.

2021-02-28 15:40 UTC, elrido commented
Looks great, thank you! @rugk, if it is fine with you as well, would you like to doing the honor of hitting that beautiful merge button, please?

2021-03-01 08:25 UTC, rugk requested changes

2021-03-01 08:25 UTC, rugk commented on tpl/page.php
> +                   <?php echo I18n::_('%s is a minimalist, open source online pastebin where the server has zero knowledge of pasted data. Data is encrypted/decrypted %sin the browser%s using 256 bit
Please change the indentation back to the original one with tabs, thanks.

2021-03-01 08:26 UTC, rugk commented
Also BTW I did not had another look in the command-line,but you co-authored with yourself in git. It may be that there is a private mail or so still in there. (But it's also in the old branch, so :shrug:)

2021-03-06 13:16 UTC, hogren commented
Last modifications weren't committed. I did it.
I refactored indentations with tabs.
I reset git config and amend the commit with --reset-author option. I see only once «hogren» now in the commit detail :)

I hope that all is good.

2021-03-06 14:00 UTC, rugk approved these changes

2021-03-07 19:04 UTC, merged