Mark line(s) to share highlighted part(s) of the paste
PrivateBin/PrivateBin pull request #762
Opened 2021-04-01 04:50 UTC by 9mido

@Tigerpanzer02 is the author of this PR

Attempts to solve https://github.com/PrivateBin/PrivateBin/issues/743

Test here:

https://paste.plugily.xyz

I wrote my opinions in the issue of how I think this should be improved because I did not quite like it completely. It works, but it is hard to use from a UX standpoint. 

I am helping @Tigerpanzer02 make a PR request so that others can help improve this code to make it more user friendly.

2021-04-01 19:00 UTC, rugk commented
Hi @9mido and @Tigerpanzer02,
thanks for your first contribution to this project! :tada: :+1: 🏅
I hope you'll like this project and enjoy hacking on it… :smiley:

First of all, thanks for bringing it into a PR form. Of course, it would be better if @Tigerpanzer02 created that PR for the reasons you stated.

BTW: Next time, try to avoid doing a pull request from the master branch, because you can run into problems when you have a "non-clean" master that does not follow this repo here (i.e. "upstream"). [See this article for details](https://help.github.com/en/articles/proposing-changes-to-your-work-with-pull-requests). Anyway, this is only a tip for the next time. :smiley:

And you can (automatically) [let issues close](https://help.github.com/articles/closing-issues-via-commit-messages/) when a PR is merged by adding some "magic" text to your PR _body_. (Manually linked it now.)

But so far off-topic stuff…

2021-04-01 19:07 UTC, rugk requested changes
Thanks for the test website.

Testing it, I still see some usability issues.
![grafik](https://user-images.githubusercontent.com/11966684/113341570-99ea1b80-932d-11eb-8285-63b2d8b60189.png)
![grafik](https://user-images.githubusercontent.com/11966684/113341612-a4a4b080-932d-11eb-9766-8c51e2da3ec2.png)
![grafik](https://user-images.githubusercontent.com/11966684/113341629-aa9a9180-932d-11eb-8f6a-1fc623bcbd37.png)

It's good for a quick mockup, but the text buttons there are a little too much IMHO.
Multi-line selecting should preferably work with drag- and dropping.
And single-line selection just can be a click, no need for a label.
Also, clearing the selecting, dunno… may be an extra button.
The term "scrolling" might also not be what we'd imagine.

As discussed in the issue too.

2021-04-01 19:07 UTC, rugk commented on tpl/bootstrap.php
> -		<!-- Twitter/social media cards -->
Your code seems to revert a lot, we already had in master, i.e. it seems to reuse old code from an old (non-development) version of PrivateBin.
As such, it's really hard to review and not possible to merge in that state, unfortunately.

2021-04-01 19:32 UTC, 9mido commented
@Tigerpanzer02 I made the PR directly from the github website I did not use any command line tools. What you need to do is fork privatebin, navigate to your fork, make a branch, make your code changes in the appropriate files by clicking the pencil edit icon on the coding files, then navigate back to the main privatebin github page, click on pull requests, and you should be able to submit a pull request from the branch you made. You need to be the one to make the PR since I am not a PHP programmer. 

When you do this, I think we should close this PR and work off of your PR instead. Or if someone from the privatebin team could make a draft PR based on what is seen here, that would work too.

2021-05-04 14:13 UTC, Tigerpanzer02 commented
Can be closed... See #789

2021-05-04 17:01 UTC, closed without merging