Limit paste creation / commenting to configurable IP addresses
PrivateBin/PrivateBin pull request #890
Opened 2022-02-20 11:05 UTC by elrido

This PR fixes #883 and replaces #622.

## Changes
* Adds an option `creators` in `traffic` section to add a list of IPs (v4 or v6) or subnets (CIDR notation)
* If not empty, these creator IPs are the only ones allowed to create pastes or comment them, but anyone can still view the pastes.
* The original PR had placed this logic into the `Controller`, but when moved to `TrafficLimiter` the logic of the exempted IPs can be reused. Downside is that I now return true or an exception, so that a (translated) error message can be passed up to the `Controller`.
* Renamed the `exemptedIps` setting to `exempted` and changed the wording of both configuration items comments, so they match.
* For reference, the overall traffic limiting logic (which only applies when creating a paste or comment) now is as follows:
  * If `creators` isn't empty and the current IP matches one of the items on the list, let it pass, otherwise block it.
  * If the limit is set to less then 1 (= disabled), let it pass.
  * If the current (sha256 hashed) IP is in the list of limited IPs AND the limit hasn't expired, block it.
  * otherwise, let it pass.

In other words, once `creators` are defined, it is the only thing checked and anything else is skipped. So it is exclusive of disabling the limit or the `exempted` IPs.

## ToDo
* [ ] Get this PR reviewed, incorporate any fixes or suggestions.
* [ ] Update the configuration settings wiki page.

2022-02-20 20:12 UTC, elrido commented
FYI: Scrutinizer warns that in newer iplib versions a few functions got deprecated, so I suggest, we upgrade the libraries first, then update this and fix the deprecations, before merging it. Mark it as WIP.

2022-02-25 05:44 UTC, elrido commented
library update is in, will get those deprecated function calls addressed on the weekend.

2022-02-25 13:03 UTC, rugk requested changes

2022-02-25 13:03 UTC, rugk commented on tst/Persistence/TrafficLimiterTest.php
> +            $this->assertEquals($e->getMessage(), 'Your IP is not authorized to create pastes.', 'request is to fast, not a creator');
```suggestion
            $this->assertEquals($e->getMessage(), 'Your IP is not authorized to create pastes.', 'not a creator');
```

The error here is that the creator IP is not whitelisted, not that the request is too fast, or is it?

And if so, we should potentially wait some seconds before that, so the error is really due to not being whitelisted, not due to being a too fast request.

2022-02-26 06:25 UTC, elrido commented
deprecated function calls got fixed, pretty ready now, IMO

2022-02-26 10:52 UTC, rugk submitted a review, later dismissed

2022-02-26 10:59 UTC, elrido commented
Ah, sorry @rugk, I wasn't fast enough. Could you approve it once more, please? I merged master into this branch (with the corsican lang) and added the new message to the co.json and regenerated the SRI hashes for privatebin.js in the templates.

2022-02-27 13:15 UTC, rugk approved these changes

2022-02-27 18:31 UTC, elrido commented on tst/Persistence/TrafficLimiterTest.php
> +        $this->assertTrue(TrafficLimiter::canPass(), 'request is to fast, but IPv4 in creator range');
The traffic limiter only applies to paste creation and commenting, never to viewing. So, yes.

2022-02-27 18:33 UTC, merged