CREATE INDEX IF NOT EXISTS is not supported as of MySQL <= 8.0
PrivateBin/PrivateBin pull request #945
Opened 2022-06-27 17:10 UTC by elrido

This PR fixes #943

## Changes
* revert to `CREATE INDEX` without `IF NOT EXISTS` clauses, to support MySQL

This issue didn't affect MariaDB, Postgres, SQLite (same code paths, different data types) or Oracle support (different logic in those areas).

2022-06-27 23:05 UTC, r4sas commented
Maybe we can split MySQL `< 8` and `>= 8` operations? Like adding config option to use old behavior without `IF NOT EXISTS`?

2022-06-28 03:43 UTC, elrido commented
> Maybe we can split MySQL `< 8` and `>= 8` operations? Like adding config option to use old behavior without `IF NOT EXISTS`?

AFAIK 8.0.23 is the latest version and there is currently no MySQL version that supports this. :-(

Also, I need to review more carefully why those unit tests failed.

2022-06-28 05:09 UTC, elrido commented
Ok, turns out those unit tests saved our beef once again - that was an actual bug that got masked by the `IF NOT EXISTS`.

The database abstraction supports an optional table prefix configuration, called `tbl`. The unit tests run with this unset as well as setting it to different values, later on:
https://github.com/PrivateBin/PrivateBin/blob/4ad4aed875e0af79b3bbe4b1ae8060567c101c8a/tst/Data/DatabaseTest.php#L14-L19
https://github.com/PrivateBin/PrivateBin/blob/4ad4aed875e0af79b3bbe4b1ae8060567c101c8a/tst/Data/DatabaseTest.php#L268-L269
https://github.com/PrivateBin/PrivateBin/blob/4ad4aed875e0af79b3bbe4b1ae8060567c101c8a/tst/Data/DatabaseTest.php#L313-L314

Whenever you get an instance, the configuration passed is updated and the tables are scanned and missing tables are created. When the prefix changes, the old tables are ignored and new tables are created alongside. The tables do get created with the prefix, so that works, but the indexes didn't use the prefix, so could not be created a second time under the same name.

This means that prior to this change, if two instances shared the same database, the index on the `pasteid` in the `comment` table would only get created for the first such table. This won't break the subsequent instances from working, but will reduce the performance when scanning for comments, when there happen to be millions of comments.

2022-06-29 18:57 UTC, r4sas requested changes

2022-06-29 18:57 UTC, r4sas commented on lib/Data/Database.php
> +            // CREATE INDEX IF NOT EXISTS not supported as of MySQL <= 8.0
Maybe we need to point that only Oracle's MySQL didn't supports this?

2022-06-29 18:57 UTC, r4sas commented on lib/Data/Database.php
> +                // CREATE INDEX IF NOT EXISTS not supported as of MySQL <= 8.0
See above.

2022-06-29 20:31 UTC, r4sas approved these changes

2022-06-30 04:43 UTC, merged