New Crowdin updates
PrivateBin/PrivateBin pull request #968
Opened 2022-08-21 15:21 UTC by privatebin-translator

2022-08-24 04:36 UTC, elrido requested changes
I guess the reverts need to be reverted upstream in Crowdin - Vandalism?

2022-08-24 04:36 UTC, elrido commented on i18n/nl.json
> -    "Could not get paste data: %s": "Kon geen klembordgegevens verkrijgen: %s",
this reverts the existing translation

2022-08-24 04:36 UTC, elrido commented on i18n/tr.json
> -    "%s is a minimalist, open source online pastebin where the server has zero knowledge of pasted data. Data is encrypted/decrypted %sin the browser%s using 256 bits AES.": "%s sunucunun burada payl
most of the translations here got reverted

2022-08-24 08:16 UTC, r4sas commented
> I guess the reverts need to be reverted upstream in Crowdin - Vandalism?

Looks like someone translated to Ukrainian, but broke other translations.

2022-09-10 19:44 UTC, r4sas commented
Okay, I had reverted broken translations... it looks for me like crowdin somehow lost them.

2022-09-11 10:49 UTC, r4sas commented
@elrido please check Crowdin for issues reports I've made about approved translations.

2022-09-18 12:01 UTC, elrido submitted a review, later dismissed

2022-09-18 12:44 UTC, elrido commented
> @elrido please check Crowdin for issues reports I've made about approved translations.

Thank you very much! I did some additional minor tweaks (replace `%s` with `%d` and the three dots with the unicode glyph) in some places and added the new Slovak translation that got requested since (I'll still need to do the changes to enable it's use in PB -> in a separate PR). I'll merge what we have so far.

2022-09-18 12:44 UTC, merged